        version: '3.1'
        services:
          stats-server:
            build: stat-service/server
            container_name: stats-service
            image: stats-service
            ports:
              - "9090:9090"
            depends_on:
              - stats-db
            environment:
              - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
              - POSTGRES_USER=postgres
              - POSTGRES_PASSWORD=iamroot

          stats-db:
            image: postgres:14-alpine
            container_name: stats-db
            ports:
              - "6541:5432"
            environment:
              - POSTGRES_DB=stats-db
              - POSTGRES_USER=postgres
              - POSTGRES_PASSWORD=iamroot
              - TZ=Europe/Moscow

          ewm-service:
            build: main-service
            container_name: main-service
            image: main-service
            ports:
              - "8080:8080"
            depends_on:
              - ewm-db
              - stats-server
            environment:
              - STATS_SERVICE_URL=http://stats-service:9090
              - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
              - POSTGRES_USER=postgres
              - POSTGRES_PASSWORD=iamroot

          ewm-db:
            image: postgres:14-alpine
            container_name: ewm-db
            ports:
              - "6542:5432"
            environment:
              - POSTGRES_DB=ewm-db
              - POSTGRES_USER=postgres
              - POSTGRES_PASSWORD=iamroot
              - TZ=Europe/Moscow